users:
  -
   user_name : 'alf_an@ukr.net'
   password: '12345678'
  -
   user_name : 'mir.fedotov@gmail.com'
   password: 'vbrvbr5352'
  -
   user_name : 'yangemba@gmail.com'
   password: 'bayan2025'

base-url: 'http://premier.ua/'

log_settings: logging.yaml

logging_type: console #can be changed to file

#timeout = timeout_base + rand(timeout_min,timeout_max)
timeout_min: 100
timeout_max: 600
timeout_base: 300

user_agents:
      - 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0)'
      - 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)'
      - 'Mozilla/4.0 (compatible; MSIE 5.5; Windows NT 5.0 )'
      - 'Mozilla/4.0 (compatible; MSIE 5.5; Windows 98; Win 9x 4.90)'
      - 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.1) Gecko/2008070208 Firefox/3.0.1'
      - 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.14) Gecko/20080404 Firefox/2.0.0.14'
      - 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/525.13 (KHTML, like Gecko) Chrome/0.2.149.29 Safari/525.13'
      - 'Mozilla/4.8 [en] (Windows NT 6.0; U)'
      - 'Mozilla/4.8 [en] (Windows NT 5.1; U)'
      - 'Opera/9.25 (Windows NT 6.0; U; en)'
      - 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; en) Opera 8.0'
      - 'Opera/7.51 (Windows NT 5.1; U) [en]'
      - 'Opera/7.50 (Windows XP; U)'
      - 'Avant Browser/1.2.789rel1 (http://www.avantbrowser.com)'
      - 'Mozilla/5.0 (Windows; U; Win98; en-US; rv:1.4) Gecko Netscape/7.1 (ax)'
      - 'Mozilla/5.0 (Windows; U; Windows XP) Gecko MultiZilla/1.6.1.0a'
      - 'Opera/7.50 (Windows ME; U) [en]'
      - 'Mozilla/3.01Gold (Win95; I)'
      - 'Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Debian/1.6-7'
      - 'Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Epiphany/1.2.5'
      - 'Mozilla/5.0 (X11; U; Linux i586; en-US; rv:1.7.3) Gecko/20050924 Epiphany/1.4.4 (Ubuntu)'
      - 'Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.10 (like Gecko) (Kubuntu)'
      - 'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.19) Gecko/20081216 Ubuntu/8.04 (hardy) Firefox/2.0.0.19'
      - 'Mozilla/5.0 (X11; U; Linux; i686; en-US; rv:1.6) Gecko Galeon/1.3.14'
      - 'Konqueror/3.0-rc4; (Konqueror/3.0-rc4; i686 Linux;;datecode)'
      - 'Mozilla/5.0 (compatible; Konqueror/3.3; Linux 2.6.8-gentoo-r3; X11;'
      - 'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.6) Gecko/20050614 Firefox/0.8'
      - 'ELinks/0.9.3 (textmode; Linux 2.6.9-kanotix-8 i686; 127x41)'
      - 'ELinks (0.4pre5; Linux 2.6.10-ac7 i686; 80x33)'
      - 'Links (2.1pre15; Linux 2.4.26 i686; 158x61)'
      - 'Links/0.9.1 (Linux 2.4.24; i386;)'
      - 'MSIE (MSIE 6.0; X11; Linux; i686) Opera 7.23'
      - 'Opera/9.52 (X11; Linux i686; U; en)'
      - 'Lynx/2.8.5rel.1 libwww-FM/2.14 SSL-MM/1.4.1 GNUTLS/0.8.12'
      - 'w3m/0.5.1'
      - 'Links (2.1pre15; FreeBSD 5.3-RELEASE i386; 196x84)'
      - 'Mozilla/5.0 (X11; U; FreeBSD; i386; en-US; rv:1.7) Gecko'
      - 'Mozilla/4.77 [en] (X11; I; IRIX;64 6.5 IP30)'
      - 'Mozilla/4.8 [en] (X11; U; SunOS; 5.7 sun4u)'
      - 'Mozilla/3.0 (compatible; NetPositive/2.1.1; BeOS)'

proxy:
      -
       'http': 'http://193.0.152.59:3128'
       'https': 'https://193.0.152.59:3128'
      -
       'http': 'http://79.120.72.222:3128'
       'https': 'https://79.120.72.222:3128'
      -
       'http': 'http://88.82.172.237:7777'
       'https': 'https://88.82.172.237:7777'

      - 
	'http':'http://51.254.106.64'
      - 
	'http':'http://210.96.153.20:3128'

